Traceback (most recent call last):
  File "/Users/sbello/Documents/personal_repos/2021_machine_learning_and_data_science/.venv/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 64, in single_nb_execution
    **kwargs,
  File "/Users/sbello/Documents/personal_repos/2021_machine_learning_and_data_science/.venv/lib/python3.7/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/sbello/Documents/personal_repos/2021_machine_learning_and_data_science/.venv/lib/python3.7/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/sbello/Documents/personal_repos/2021_machine_learning_and_data_science/.venv/lib/python3.7/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/sbello/.pyenv/versions/3.7.17/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/Users/sbello/Documents/personal_repos/2021_machine_learning_and_data_science/.venv/lib/python3.7/site-packages/nbclient/client.py", line 664, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/Users/sbello/Documents/personal_repos/2021_machine_learning_and_data_science/.venv/lib/python3.7/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/sbello/Documents/personal_repos/2021_machine_learning_and_data_science/.venv/lib/python3.7/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# La multiplicaci√≥n entre listas no est√° permitida.
ls_a * ls_b # Si se descomenta esta sentencia saldr√° un error
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
[0;32m/var/folders/k0/k1ptdl95457___jzhps_pq4r8286v9/T/ipykernel_80967/3196884061.py[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0;31m# La multiplicaci√≥n entre listas no est√° permitida.[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 2[0;31m [0mls_a[0m [0;34m*[0m [0mls_b[0m [0;31m# Si se descomenta esta sentencia saldr√° un error[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;31mTypeError[0m: can't multiply sequence by non-int of type 'list'
TypeError: can't multiply sequence by non-int of type 'list'

